### ISSUE TITLE
Possible bug in HandlesCartItems trait

### ISSUE THREAD

**Issue by lautaroml** [Yiddishe-Kop/laravel-commerce#5]
Expected behavior should be the increase of the quantity of a cart item. But I'm getting a new inserted row.

Explanation:

In line 18 of HandlesCartItems trait, you are always grabbing from DB the first item in the cart, no matter what.

Suppose, you have 2 items in the cart, with the same model_id and model_type but with different options:

| id | order_id | model_type         | model_id | quantity | options        | title | price | discount |
|----|----------|--------------------|----------|----------|----------------|-------|-------|----------|
|  1 |        1 | App\Models\Product |        1 |        1 | {"size": "sm"} | Shirt |   100 |        0 |
|  2 |        1 | App\Models\Product |        1 |        1 | {"size": "xl"} | Shirt |   100 |        0 |

Then, every time I  try to add a product with model_type = 1, model_id = 1, and size = xl, the line 18 will only get the item with the id of 1. Because its grabbing, no matter what, the first one.

So, when I add the product the order_items table will look like these (wrong):

| id | order_id | model_type         | model_id | quantity | options        | title | price | discount |
|----|----------|--------------------|----------|----------|----------------|-------|-------|----------|
|  1 |        1 | App\Models\Product |        1 |        1 | {"size": "sm"} | Shirt |   100 |        0 |
|  2 |        1 | App\Models\Product |        1 |        1 | {"size": "xl"} | Shirt |   100 |        0 |
|  3 |        1 | App\Models\Product |        1 |        1 | {"size": "xl"} | Shirt |   100 |        0 |

Instead of (correct):

| id | order_id | model_type         | model_id | quantity | options        | title | price | discount |
|----|----------|--------------------|----------|----------|----------------|-------|-------|----------|
|  1 |        1 | App\Models\Product |        1 |        1 | {"size": "sm"} | Shirt |   100 |        0 |
|  2 |        1 | App\Models\Product |        1 |        2 | {"size": "xl"} | Shirt |   100 |        0 |

And if I keep adding products with model_type = 1, model_id = 1, and size = xl, every time I add that product, a new row will be inserted in the order_items table, when the expected behavior should be the increase of the quantity of the item with the id of 2.

**Comment by Yiddishe-Kop** [comment]
Great catch @lautaroml, thanks a lot! 😀

**Comment by Yiddishe-Kop** [comment]
Fixed with #6
